(()=>{
"use strict";
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const ui={host:$("#sceneHost"),loading:$("#loadingScene"),search:$("#search"),counter:$("#counter"),wing:$("#wingRail"),guide:$("#guidePanel"),guideBtn:$("#guideBtn"),guideClose:$("#guideClose"),groups:$("#guideGroups"),cats:$("#categoryGrid"),results:$("#guideResults"),resultSummary:$("#resultSummary"),crumb:$("#crumb"),desk:$("#bookDesk"),deskClose:$("#deskClose"),deskImg:$("#deskImg"),deskFallback:$("#deskFallback"),deskTitle:$("#deskTitle"),deskAuthor:$("#deskAuthor"),deskSummary:$("#deskSummary"),deskTags:$("#deskTags"),deskKicker:$("#deskKicker"),openBtn:$("#openBookBtn"),downloadBtn:$("#downloadBookBtn"),hover:$("#hoverCard"),prev:$("#prevShelf"),next:$("#nextShelf"),page:$("#pageLabel"),loc:$("#locationBadge"),toast:$("#toast"),empty:$("#emptyState"),emptyTitle:$("#emptyTitle"),emptyCopy:$("#emptyCopy"),emptyReset:$("#emptyReset")};
const prefix=location.pathname.includes("/v7/")?"../":"", reducedMotion=matchMedia("(prefers-reduced-motion: reduce)").matches, state={all:[],filtered:[],collection:"",group:"",category:"",keyword:"",page:0,perPage:180,local:false,config:{downloadBase:""},activeBook:null,lastFocus:null};
ui.guide.hidden=true;ui.desk.hidden=true;ui.empty.hidden=true;
let scene,camera,renderer,world,raycaster,pointer,shelfSlots=[],bookMeshes=[],signMeshes=[],hovered=null,activeMesh=null,targetZ=9,targetX=0,targetY=2.35,mouseX=0,mouseY=0,entered=false,animationId=0,touchStart=null,suppressClickUntil=0;
const palette=[0x7b4b38,0x9b6a48,0x52665a,0x687278,0x8d7657,0x5d493f,0x3f5a56,0x977f67,0x6a5c72,0x4e646f,0x8a5f55,0x6c7358];
function clamp(v,a,b){return Math.max(a,Math.min(b,v))} function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function toast(msg){ui.toast.textContent=msg;ui.toast.classList.add("show");clearTimeout(toast._t);toast._t=setTimeout(()=>ui.toast.classList.remove("show"),1800)}
function assetUrl(path){if(!path)return"";return prefix+String(path).replace(/\\/g,"/")} function encodePath(path){return String(path||"").split(/[\\/]/).map(encodeURIComponent).join("/")}
async function getJSON(url){const r=await fetch(url,{cache:"no-store"});if(!r.ok)throw new Error(r.status+" "+url);return r.json()}
async function loadData(){try{const [books]=await Promise.all([getJSON("/api/books")]);state.all=books.books||[];state.local=true}catch(_){const books=await getJSON(prefix+"books.json");state.all=books.books||[];state.local=false;try{state.config=await getJSON(prefix+"config.json")}catch(_e){state.config={downloadBase:""}}}return state.all}
function initScene(){
try{renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:"high-performance"})}catch(err){document.body.classList.add("no-webgl");return false}renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.6));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.04;if("outputColorSpace"in renderer)renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.setClearColor(0xd7d4ca,1);ui.host.prepend(renderer.domElement);
scene=new THREE.Scene();scene.fog=new THREE.Fog(0xd6d3ca,18,45);camera=new THREE.PerspectiveCamera(46,innerWidth/innerHeight,.08,100);camera.position.set(0,2.35,9);raycaster=new THREE.Raycaster();pointer=new THREE.Vector2(9,9);world=new THREE.Group();scene.add(world);
scene.add(new THREE.HemisphereLight(0xf4f6f1,0x5e5246,1.6));const sun=new THREE.DirectionalLight(0xf7fbff,2.9);sun.position.set(-6,13,8);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-16;sun.shadow.camera.right=16;sun.shadow.camera.top=18;sun.shadow.camera.bottom=-4;scene.add(sun);const warm=new THREE.PointLight(0xffd9a0,5.4,28,2);warm.position.set(0,5.8,-8);scene.add(warm);
buildArchitecture();bindSceneEvents();resize();animationId=requestAnimationFrame(tick);return true;
}
const mats={};
function material(key,color,rough=.65,metal=.05,extra={}){if(!mats[key])mats[key]=new THREE.MeshStandardMaterial(Object.assign({color,roughness:rough,metalness:metal},extra));return mats[key]}
function box(w,h,d,x,y,z,mat,parent=world,cast=false){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);m.castShadow=cast;m.receiveShadow=true;parent.add(m);return m}
function cyl(r1,r2,h,x,y,z,mat,parent=world){const m=new THREE.Mesh(new THREE.CylinderGeometry(r1,r2,h,28),mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
function buildArchitecture(){
const floor=material("floor",0xc1b5a4,.82,.02), concrete=material("concrete",0xd7d5cf,.9,.01),oak=material("oak",0x9a6b47,.58,.04),oakDark=material("oakDark",0x6a4936,.62,.03),metal=material("metal",0x292d2a,.34,.72),glass=material("glass",0xc8d7d9,.18,.1,{transparent:true,opacity:.32}),green=material("green",0x5b6c60,.78,.02),fabric=material("fabric",0x7f7466,.98,0),white=material("white",0xf0efe9,.76,.02);
box(18,.22,40,0,-.12,-8,floor);box(18,.35,40,0,7.2,-8,concrete);box(.3,7.4,40,-9,3.55,-8,concrete);box(.3,7.4,40,9,3.55,-8,concrete);
for(let z=8;z>-29;z-=4){box(18,.018,.035,0,.01,z,metal);box(.035,.018,40,z%8?-4:4,.011,-8,metal)}
box(16.4,6.2,.18,0,3.1,-28,glass);for(let x=-8;x<=8;x+=2.05)box(.055,6.3,.2,x,3.1,-27.9,metal);for(let y=.2;y<=6.3;y+=2.05)box(16.4,.055,.2,0,y,-27.9,metal);
for(let z=5;z>-27;z-=5.2){box(6.4,.06,.34,0,6.82,z,material("light",0xfff3d4,.35,.04,{emissive:0xffe5b4,emissiveIntensity:2.5}));const l=new THREE.PointLight(0xffe6bf,1.9,11,2);l.position.set(0,6.25,z);scene.add(l)}
for(const x of[-6.6,6.6]){box(3.9,.34,25,x,5.25,-10,concrete);for(let z=1;z>-24;z-=3.5){box(.08,1.25,.08,x>0?4.82:-4.82,5.65,z,metal);box(.08,1.25,.08,x>0?8.45:-8.45,5.65,z,metal);box(3.7,.07,.08,x,6.12,z,metal)}}
const zUnits=[2,-3,-8,-13,-18,-23];for(const z of zUnits)for(const side of[-1,1])buildShelf(side,z,oak,oakDark,metal);
box(4.2,.92,1.5,0,.48,4.7,oakDark,world,true);box(3.65,.08,1.15,0,.98,4.7,white);box(.12,1.45,.12,-1.55,1.7,4.7,metal);box(2.6,.06,.8,0,2.42,4.7,material("deskSign",0xe8e5dd,.5,.05)); 
for(const z of[-6,-16]){box(3.9,.13,1.15,0,.7,z,oak);box(.18,1.35,.18,-1.55,.04,z,metal);box(.18,1.35,.18,1.55,.04,z,metal);for(const x of[-2.55,2.55]){box(1.2,.23,.72,x,.48,z,fabric);box(.14,.85,.14,x-.4,.0,z,metal);box(.14,.85,.14,x+.4,.0,z,metal)}}
for(const z of[-1,-11,-21]){cyl(.55,.62,.6,-2.6,.28,z,material("planter",0x79736a,.8,.02));const trunk=cyl(.08,.1,1.15,-2.6,1.1,z,oakDark);for(let i=0;i<7;i++){const leaf=new THREE.Mesh(new THREE.SphereGeometry(.3+.08*(i%2),10,8),green);leaf.scale.set(1,.55,1);leaf.position.set(-2.6+(i%3-1)*.34,1.45+Math.floor(i/3)*.24,z+(i%2?-.18:.18));world.add(leaf)}}
}
function buildShelf(side,z,oak,oakDark,metal){
const g=new THREE.Group();g.position.set(side*5.8,0,z);world.add(g);const frontX=-side*.72;box(1.05,5.05,4.15,0,2.55,0,material("shelfBack",0x856249,.72,.02),g);box(.12,5.35,4.34,frontX,2.6,0,metal,g);
for(const dz of[-2.08,2.08])box(1.16,5.35,.13,0,2.6,dz,oakDark,g);for(const y of[.35,1.35,2.35,3.35,4.35,5.28])box(1.18,.12,4.25,0,y,0,oak,g);
for(let level=0;level<5;level++)for(let j=0;j<13;j++)shelfSlots.push({side,z:z-1.75+j*.29,y:.48+level,x:side*(5.15+.02*(j%2)),level,index:shelfSlots.length});
}
function clearBooks(){for(const m of bookMeshes){m.parent&&m.parent.remove(m);m.geometry.dispose();m.material&&m.material.dispose&&m.material.dispose()}bookMeshes=[];hovered=null;activeMesh=null}
function bookColor(book,i){const seed=String(book.title||book.category||i).split("").reduce((a,c)=>a+c.charCodeAt(0),0);return palette[Math.abs(seed)%palette.length]}
function rebuildBooks(){
clearBooks();const start=state.page*state.perPage,list=state.filtered.slice(start,start+state.perPage),count=Math.min(list.length,shelfSlots.length);for(let i=0;i<count;i++){const b=list[i],slot=shelfSlots[i],h=.66+((i*17)%11)*.022,w=.14+((i*13)%8)*.014;const mat=new THREE.MeshStandardMaterial({color:bookColor(b,i),roughness:.58,metalness:.02});const m=new THREE.Mesh(new THREE.BoxGeometry(.34,h,w),mat);m.position.set(slot.x,slot.y+h/2,slot.z);m.castShadow=true;m.receiveShadow=true;m.userData={book:b,home:m.position.clone(),side:slot.side,index:start+i,pull:0};world.add(m);bookMeshes.push(m)}updatePager();
}
function countBy(field,list){const m=new Map();for(const b of list){const k=b&&b[field];if(k)m.set(k,(m.get(k)||0)+1)}return [...m].sort((a,b)=>b[1]-a[1])}
function matchesKeyword(b){const q=state.keyword.trim().toLowerCase();if(!q)return true;const hay=[b.title,b.author,b.category,b.subcategory,b.collection,b.group].filter(Boolean).join(" ").toLowerCase();return hay.includes(q)}
function baseList(ignoreCategory=false){return state.all.filter(b=>(!state.collection||b.collection===state.collection)&&(!state.group||b.group===state.group)&&((ignoreCategory||!state.category)||b.category===state.category)&&matchesKeyword(b))}
function applyFilters(reset=true){
if(state.activeBook)closeDesk();state.filtered=state.all.filter(b=>(!state.collection||b.collection===state.collection)&&(!state.group||b.group===state.group)&&(!state.category||b.category===state.category)&&matchesKeyword(b));if(reset)state.page=0;state.perPage=Math.min(180,Math.max(1,shelfSlots.length));rebuildBooks();renderUI();rebuildSigns();
}
function rebuildSigns(){
 if(!world)return;for(const m of signMeshes){m.parent&&m.parent.remove(m);m.geometry.dispose();if(m.material&&m.material.map)m.material.map.dispose();m.material&&m.material.dispose&&m.material.dispose()}signMeshes=[];const cats=countBy("category",baseList(true)).slice(0,5),zs=[1,-4,-9,-14,-19];cats.forEach(([name,count],i)=>{const tex=signTexture(name,count),mat=new THREE.MeshBasicMaterial({map:tex,transparent:true,depthTest:true});const mesh=new THREE.Mesh(new THREE.PlaneGeometry(2.8,.72),mat);mesh.position.set(0,5.45,zs[i]);mesh.userData={category:name,count,sign:true};world.add(mesh);signMeshes.push(mesh)});
}
function signTexture(name,count){const c=document.createElement("canvas");c.width=1024;c.height=256;const x=c.getContext("2d");x.fillStyle="rgba(244,243,236,.96)";x.fillRect(0,0,c.width,c.height);x.strokeStyle="rgba(30,34,30,.16)";x.lineWidth=3;x.strokeRect(3,3,c.width-6,c.height-6);x.fillStyle="#232721";x.font='600 54px "Microsoft YaHei",sans-serif';x.textAlign="center";x.fillText(name,c.width/2,112);x.fillStyle="#7c7f78";x.font='500 28px sans-serif';x.fillText(count+" 册 · COLLECTION",c.width/2,174);const t=new THREE.CanvasTexture(c);if("colorSpace"in t)t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=4;return t}
function renderResults(){const visible=state.filtered.slice(0,18);ui.resultSummary.textContent=state.filtered.length?`显示 ${visible.length} / ${state.filtered.length} 本`:"没有匹配书籍";ui.results.innerHTML=visible.map((b,i)=>`<button class="resultRow" type="button" data-book-index="${i}" aria-label="打开《${esc(b.title||"未命名")}》详情"><span><b>${esc(b.title||"未命名")}</b><span>${esc([b.author,b.category].filter(Boolean).join(" · ")||"未标注作者")}</span></span><em>查看</em></button>`).join("")+(state.filtered.length>visible.length?`<div class="resultMore">还有 ${state.filtered.length-visible.length} 本，请用分页或继续缩小范围</div>`:"")||'<div class="guideSearchHint">当前筛选下没有可浏览的书籍。</div>'}
function renderUI(){
ui.counter.textContent=state.filtered.length+" / "+state.all.length+" 册";ui.counter.setAttribute("aria-label",`当前显示 ${state.filtered.length} 本，共 ${state.all.length} 本`);const loc=[state.collection||"全馆",state.group,state.category].filter(Boolean);ui.crumb.textContent=loc.join(" · ")+" · "+state.filtered.length+" 册";ui.loc.querySelector("span").textContent=state.category||state.group||state.collection||"入口大厅";ui.loc.querySelector("small").textContent=state.category?"COLLECTION AISLE":"GROUND FLOOR";
const collections=countBy("collection",state.all);ui.wing.innerHTML='<button class="wingChip '+(!state.collection?"on":"")+'" data-coll="" aria-pressed="'+(!state.collection)+'">全馆</button>'+collections.map(([n,c])=>'<button class="wingChip '+(state.collection===n?"on":"")+'" data-coll="'+esc(n)+'" aria-pressed="'+(state.collection===n)+'">'+esc(n)+' · '+c+"</button>").join("");
const groupSource=state.all.filter(b=>(!state.collection||b.collection===state.collection)&&matchesKeyword(b)),groups=countBy("group",groupSource);ui.groups.innerHTML='<button class="groupChip '+(!state.group?"on":"")+'" data-group="" aria-pressed="'+(!state.group)+'">全部分组</button>'+groups.map(([n,c])=>'<button class="groupChip '+(state.group===n?"on":"")+'" data-group="'+esc(n)+'" aria-pressed="'+(state.group===n)+'">'+esc(n)+" · "+c+"</button>").join("");
const cats=countBy("category",baseList(true));ui.cats.innerHTML=cats.map(([n,c])=>'<button class="categoryCard '+(state.category===n?"on":"")+'" data-cat="'+esc(n)+'" aria-pressed="'+(state.category===n)+'"><b>'+esc(n)+'</b><span>'+c+" 册 · 点击进入书区</span></button>").join("")||'<div class="guideSearchHint">当前筛选下没有分类。</div>';renderResults();const empty=!state.filtered.length;ui.empty.classList.toggle("show",empty);ui.empty.hidden=!empty;ui.empty.setAttribute("aria-hidden",String(!empty));if(empty){ui.emptyTitle.textContent=state.keyword?"没有找到匹配的书":"当前馆区还没有书";ui.emptyCopy.textContent=state.keyword?`没有包含“${state.keyword}”的馆藏，换个关键词试试。`:"换一个馆区，或回到全馆继续浏览。"}else{ui.emptyTitle.textContent="没有找到匹配的书";ui.emptyCopy.textContent="换一个关键词，或回到全馆继续浏览。"}
}
function updatePager(){const pages=Math.max(1,Math.ceil(state.filtered.length/state.perPage));state.page=clamp(state.page,0,pages-1);ui.page.textContent="第 "+(state.page+1)+" / "+pages+" 架 · "+state.filtered.length+" 本";ui.prev.disabled=state.page<=0;ui.next.disabled=state.page>=pages-1}
function setCollection(v){state.collection=v;state.group="";state.category="";state.page=0;applyFilters();enterLibrary();targetZ=2.5}
function setGroup(v){state.group=v;state.category="";state.page=0;applyFilters();enterLibrary();targetZ=-2}
function setCategory(v){state.category=v;state.page=0;applyFilters();enterLibrary();targetZ=-5;closeGuide();toast("已进入 "+v+" 书区")}
function enterLibrary(){entered=true;document.body.classList.add("entered");targetZ=Math.min(targetZ,3.5)}
function resetAll(){state.collection=state.group=state.category=state.keyword="";state.page=0;ui.search.value="";applyFilters();targetZ=9;entered=false;document.body.classList.remove("entered");closeDesk();closeGuide()}
function restoreFocus(){const el=state.lastFocus;state.lastFocus=null;if(el&&el.isConnected)requestAnimationFrame(()=>el.focus())}
function openGuide(){if(!state.lastFocus)state.lastFocus=document.activeElement;ui.guide.hidden=false;ui.guide.classList.add("show");ui.guide.setAttribute("aria-hidden","false");document.body.classList.add("guide-open");requestAnimationFrame(()=>ui.guideClose.focus())}function closeGuide(){ui.guide.classList.remove("show");ui.guide.hidden=true;ui.guide.setAttribute("aria-hidden","true");document.body.classList.remove("guide-open");if(!ui.desk.classList.contains("show"))restoreFocus()}
function showBook(book,mesh){if(ui.guide.classList.contains("show"))closeGuide();if(!state.activeBook)state.lastFocus=document.activeElement;state.activeBook=book;activeMesh=mesh||null;ui.deskTitle.textContent=book.title||"未命名";ui.deskAuthor.textContent=book.author?"作者 · "+book.author:"作者未标注";ui.deskSummary.textContent=book.summary||"暂无内容简介。";ui.deskKicker.textContent=[book.collection,book.group,book.category].filter(Boolean).join(" · ")||"馆藏详情";ui.deskTags.innerHTML=[book.format&&book.format.toUpperCase(),book.source,book.rating!=null?((book.ratingPlatform||"评分")+" "+book.rating):null].filter(Boolean).map(x=>"<span>"+esc(x)+"</span>").join("");
const cover=assetUrl(book.cover);ui.deskFallback.textContent=(book.title||"书").trim().slice(0,1);ui.deskFallback.style.display="grid";ui.deskImg.style.display="none";if(cover){ui.deskImg.onload=()=>{ui.deskImg.style.display="block";ui.deskFallback.style.display="none"};ui.deskImg.onerror=()=>{ui.deskImg.style.display="none";ui.deskFallback.style.display="grid"};ui.deskImg.src=cover}
const format=String(book.format||"pdf").toUpperCase();ui.deskImg.alt=(book.title||"书籍")+"封面";ui.openBtn.textContent=state.local?"打开书籍":"打开文件";ui.downloadBtn.textContent="下载 "+format;const dl=downloadUrl(book);if(dl){ui.downloadBtn.href=dl;ui.downloadBtn.hidden=false}else ui.downloadBtn.hidden=true;ui.desk.hidden=false;ui.desk.classList.add("show");ui.desk.setAttribute("aria-hidden","false");document.body.classList.add("details-open");requestAnimationFrame(()=>ui.deskClose.focus())}
function closeDesk(){ui.desk.classList.remove("show");ui.desk.hidden=true;ui.desk.setAttribute("aria-hidden","true");document.body.classList.remove("details-open");if(activeMesh)activeMesh.userData.pull=0;activeMesh=null;state.activeBook=null;restoreFocus()}
function downloadUrl(book){if(state.local)return"/api/download?path="+encodeURIComponent(book.path);const base=String(state.config.downloadBase||"").trim();return base?base.replace(/\/$/,"")+"/"+encodePath(book.path):""}
async function openCurrent(){const b=state.activeBook;if(!b)return;if(state.local){try{const r=await fetch("/api/open",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({path:b.path})});if(!r.ok)throw new Error();toast("已交给系统阅读器打开")}catch(_){toast("打开失败，请使用下载按钮")}}else{const u=downloadUrl(b);if(u)window.open(u,"_blank","noopener");else toast("静态预览未配置书籍地址")}}
function bindSceneEvents(){
 const pickAt=e=>{const r=renderer.domElement.getBoundingClientRect();pointer.x=((e.clientX-r.left)/r.width)*2-1;pointer.y=-((e.clientY-r.top)/r.height)*2+1;raycaster.setFromCamera(pointer,camera);return raycaster.intersectObjects([...bookMeshes,...signMeshes],false)[0]};
 renderer.domElement.addEventListener("pointermove",e=>{if(e.pointerType==="touch")return;const hit=pickAt(e);setHovered(hit?hit.object:null,e.clientX,e.clientY)});
 renderer.domElement.addEventListener("pointerdown",e=>{if(e.pointerType==="touch")touchStart={x:e.clientX,y:e.clientY}});renderer.domElement.addEventListener("pointerup",e=>{if(e.pointerType!=="touch"||!touchStart)return;const dy=e.clientY-touchStart.y;touchStart=null;if(Math.abs(dy)>26){e.preventDefault();suppressClickUntil=performance.now()+350;enterLibrary();targetZ=clamp(targetZ+dy*.025,-21,9)}});
 renderer.domElement.addEventListener("pointerleave",()=>setHovered(null));renderer.domElement.addEventListener("click",e=>{if(e.pointerType==="touch"&&performance.now()<suppressClickUntil)return;const hit=pickAt(e);if(!hit)return;const m=hit.object;if(m.userData.sign){setCategory(m.userData.category);return}if(m.userData.book){m.userData.pull=1;setTimeout(()=>showBook(m.userData.book,m),reducedMotion?0:240)}});
addEventListener("pointermove",e=>{mouseX=(e.clientX/innerWidth-.5)*2;mouseY=(e.clientY/innerHeight-.5)*2},{passive:true});
addEventListener("wheel",e=>{if(e.target.closest&&e.target.closest(".guidePanel,.bookDesk"))return;enterLibrary();targetZ=clamp(targetZ+e.deltaY*-.012,-21,9)},{passive:true});
}
function setHovered(mesh,x=0,y=0){if(hovered===mesh){if(mesh&&mesh.userData.book){ui.hover.style.left=Math.min(x,innerWidth-300)+"px";ui.hover.style.top=Math.min(y,innerHeight-90)+"px"}return}if(hovered&&hovered.userData)hovered.userData.hover=0;hovered=mesh;renderer.domElement.style.cursor=mesh?"pointer":"default";if(!mesh){ui.hover.classList.remove("show");return}mesh.userData.hover=1;if(mesh.userData.book){const b=mesh.userData.book;ui.hover.querySelector("b").textContent=b.title||"未命名";ui.hover.querySelector("span").textContent=[b.author,b.category].filter(Boolean).join(" · ")||"点击抽出这本书";ui.hover.style.left=Math.min(x,innerWidth-300)+"px";ui.hover.style.top=Math.min(y,innerHeight-90)+"px";ui.hover.classList.add("show")}else ui.hover.classList.remove("show")}
function tick(){
const tx=targetX+mouseX*.28,ty=targetY-mouseY*.08;camera.position.x+=(tx-camera.position.x)*.045;camera.position.y+=(ty-camera.position.y)*.045;camera.position.z+=(targetZ-camera.position.z)*.05;camera.lookAt(camera.position.x*.08,2.05,camera.position.z-8.5);
for(const m of bookMeshes){const u=m.userData,home=u.home,pull=u.pull?1:(u.hover?.24:0),inward=-u.side*.72*pull;m.position.x+=(home.x+inward-m.position.x)*.12;m.position.y+=(home.y+(u.pull?.18:u.hover?.06:0)-m.position.y)*.12;m.rotation.y+=(u.side*(u.pull?-.28:u.hover?-.09:0)-m.rotation.y)*.1;const s=u.pull?1.1:u.hover?1.035:1;m.scale.x+=(s-m.scale.x)*.12;m.scale.y+=(s-m.scale.y)*.12;m.scale.z+=(s-m.scale.z)*.12}
renderer.render(scene,camera);animationId=requestAnimationFrame(tick);
}
function resize(){if(!renderer)return;const w=innerWidth,h=innerHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}
function bindUI(){
 $("#enterBtn").addEventListener("click",()=>{enterLibrary();targetZ=2.8});$("#homeBtn").addEventListener("click",resetAll);$("#resetBtn").addEventListener("click",resetAll);ui.guideBtn.addEventListener("click",()=>ui.guide.classList.contains("show")?closeGuide():openGuide());ui.guideClose.addEventListener("click",closeGuide);ui.deskClose.addEventListener("click",closeDesk);ui.openBtn.addEventListener("click",openCurrent);ui.emptyReset.addEventListener("click",resetAll);
 ui.wing.addEventListener("click",e=>{const b=e.target.closest("[data-coll]");if(b)setCollection(b.dataset.coll)});ui.groups.addEventListener("click",e=>{const b=e.target.closest("[data-group]");if(b)setGroup(b.dataset.group)});ui.cats.addEventListener("click",e=>{const b=e.target.closest("[data-cat]");if(b)setCategory(b.dataset.cat)});
 ui.results.addEventListener("click",e=>{const row=e.target.closest("[data-book-index]");if(!row)return;const book=state.filtered[Number(row.dataset.bookIndex)];if(book){enterLibrary();showBook(book)}});
 ui.prev.addEventListener("click",()=>{if(state.page>0){state.page--;rebuildBooks();targetZ=-2}});ui.next.addEventListener("click",()=>{const pages=Math.ceil(state.filtered.length/state.perPage);if(state.page<pages-1){state.page++;rebuildBooks();targetZ=-2}});
 let timer=0;ui.search.addEventListener("input",()=>{clearTimeout(timer);timer=setTimeout(()=>{state.keyword=ui.search.value;state.category="";applyFilters();enterLibrary();targetZ=-2;if(state.keyword)toast("馆内找到 "+state.filtered.length+" 本匹配书籍")},120)});
 addEventListener("keydown",e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();ui.search.focus();ui.search.select();return}if(e.key==="Escape"){if(ui.desk.classList.contains("show"))closeDesk();else if(ui.guide.classList.contains("show"))closeGuide();return}const dialog=ui.desk.classList.contains("show")?ui.desk:ui.guide.classList.contains("show")?ui.guide:null;if(e.key==="Tab"&&dialog){const items=[...dialog.querySelectorAll("button,a,input,[tabindex]:not([tabindex='-1'])")].filter(el=>!el.disabled&&el.offsetParent!==null);if(items.length){const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}return}if(e.key==="ArrowDown"&&!e.target.matches("input")){targetZ=clamp(targetZ-2.4,-21,9);enterLibrary()}if(e.key==="ArrowUp"&&!e.target.matches("input"))targetZ=clamp(targetZ+2.4,-21,9)});
}
async function boot(){
try{bindUI();await loadData();const hasScene=initScene();state.filtered=state.all.slice();applyFilters();window.V7Library={ready:true,get bookCount(){return state.all.length},get filteredCount(){return state.filtered.length},get visibleBooks(){return bookMeshes.length},get signs(){return signMeshes.length},get page(){return state.page+1},get location(){return state.category||state.group||state.collection||"入口大厅"},renderer,scene,camera};if(!hasScene)openGuide();ui.loading.classList.add("ready");setTimeout(()=>ui.loading.remove(),900)}catch(err){console.error(err);window.V7Library={ready:false,error:String(err&&err.message||err)};ui.loading.innerHTML="<b>图书馆打开失败</b><small>"+esc(err.message||err)+"</small>"}
}
boot();
})();
